//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> IdEvent { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<System.TimeSpan> TimeStart { get; set; }
        public Nullable<int> IdWinner { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual User User { get; set; }
    }
}
